version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
<<<<<<< HEAD
=======
    groups:
      docusaurus:
        patterns:
          - '@docusaurus/*'
      react:
        patterns:
          - react
          - react-dom
>>>>>>> upstream/main
