version: "2.1"
services:
  site:
    container_name: jhipster.github.io
    command: jekyll serve
    image: jekyll/jekyll:3.8
    volumes:
      - ./:/srv/jekyll
      # this volume will keep all gems
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
